# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 625a8f0c6f165d5f1d699a01c831db9fa398a2e3365a58e94f97216c70f2d5cf2dfdf7a36ed9d229e73bc7b83902055824f666c6aaf00b9d931b357fbdcdc1dd

test:
  secret_key_base: f1548a3c4b8e848a7fc451ec9f254bfe0bbddff6ce4db942b497f6e036db6c06811e1f6c22c6d01c4db730e9e13deec324b2084e9e5099c2cc056e280c56572c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
